KyoriPowered/adventure-webui

src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/editor/EditorRoute.kt
Checking for a malformed or incomplete (including empty) request body is already done by the `tryDecodeFromString` method
This change allows for using the editor API to create a new message (with its {token} command generation features), rather than edit an already existing one
=> Remove input isBlank check

src/commonMain/resources/web/index.html
Removes `has-fixed-size` from input box. Bulma already seems to already make textareas be `resize: vertical` only by default, so the input and output will still match in width.
This does result in some visual jank with the background image but at least it's functional?
=> Allow input box to be resized taller than 4 rows

src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Minimessage (no longer?) doesn't convert the escape sequence `\n` to a newline, so escaping the newlines doesn't make much sense.
From the point of this request onwards, all requests bodies are in pure plaintext, so no escaping will be lost
Currently, an user of the API will receive a string with escaped newlines and will need to convert them for example with `.replace("\\n", "\n")` to get an output comparable to what is shown on the website preview
=> Preserve newline characters as single newline characters

src/commonMain/kotlin/net/kyori/adventure/webui/Constants.kt, src/commonMain/resources/web/css/style.css, src/commonMain/resources/web/index.html, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/hook/StandardRenderHooks.kt
Working towards #22. I removed the style i had before because of license stuff but the rest of the code is there.
Not the best so i'm hoping for help with it, in particular the three event listeners look bad and ~~i'm not sure if there's a better way to not have things like `"show_text"` hard-coded~~
How it works is literally by showing the whole html of the hover into a data value thing and on mouseover just puts it into a high z-index absolute position div using `innerHTML`, which is then moved around
This PR intentionally skips show_entity and show_item hover events because hhhhhhhhhhhhh
[DEMO HOSTED HERE](https://webui.hydra.rymiel.space/?mode=chat_closed&input=%3Chover%3Ashow_text%3A%27hello%20%3Cred%3Eworld%3C%2Fred%3E%27%3Ehover%20me!%3C%2Fhover%3E)
=> Show text hover events

readme.md, src/commonMain/resources/web/css/style.css
This PR fixes #42 and replaces https with http in the deployment url in the readme, because the server doesn't seem to serve https requests.
=> Fix readme and centered motd

src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
=> Don't include placeholder parameters when there aren't any

src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
As suggested by Glare [on Discord](https://canary.discord.com/channels/319355592605040642/420342659115122688/917981720714829864), it's a good idea to confirm whether a user really wants to leave the page if they have text entered, just to make sure they don't lose their progress.
Fixes #64.
=> Ask for confirmation when unloading

src/jsMain/kotlin/net/kyori/adventure/webui/js/Background.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/PersistentStorage.kt
Resolves #37.
Unifies the logic of the URL parameters with localStorage. Changes are saved live to localStorage.
When opening a shared URL, the passed values from the parameters will be used, in other cases, localStorage is tried.
Also adds the background type into the shared URL (for example, [this link will always give you the "desert" background!](https://webui.hydra.rymiel.space/?mode=hologram&input=Hello%20desert!&bg=desert))
=> Persistent settings storage

gradle/libs.versions.conf, src/commonMain/kotlin/net/kyori/adventure/webui/websocket/Packet.kt, src/commonMain/resources/web/index.html, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/UserPlaceholder.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt, src/jvmMain/resources/application.conf
Currently the webui interacts with things I'd consider to be implementation details within MM itself in order to get the tree, and so has not been modified for the removal of `Context.of`.
I believe MiniMessage will need to have some view of the parse tree exposed in order to fully update the webui for new changes.
=> Begin updating for MM changes in adventure 4.10.0

src/commonMain/resources/web/css/style.css, src/commonMain/resources/web/index.html, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Creates an extra layer around the output `pre` tag, which causes some jank CSS as most, but not all styles that were previously on `output-pane` now go on this layer instead. I could not find a better way to organize these while also keeping the icon where it should be. (at least it fixes a different jank)
Also makes the server list name white, as it is in-game. Also fixes server list's no text shadow not applying always.
Note: The width value of 546px is completely arbitrary and chosen only by how large the box was previously, there's probably a better or more accurate value that goes here
=> Revamp server list to include header in HTML, not when parsing

src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Noticed while writing something else, apparently nobody else caught this
=> Fix: JSON and tree exports not using placeholders

src/commonMain/kotlin/net/kyori/adventure/webui/websocket/Packet.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt
Currently, the backend splits all newlines and parses the split-up
messages with completely separate MiniMessage instances so they have
separate parents. With this change, this will be only done when in lore
mode, and newlines will simply remain in the message regularly in all
other modes.
The justification for this is the fact that newlines can't appear in
lores at all, as the client will render them in a tofubox. Therefore
having newlines in the lore mode in the webui implies the fact that
these are in fact separate lines with separate tree roots.
This isn't explained on the site though, maybe it should be...
Part one of making webui less horrible with newlines
=> Only handle newlines as separate parses when in lore mode

src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
As part of #79 I ripped out a hack which reparsed the message when switching modes, however, without this, after #81 switching between lore and non-lore mode wouldn't update the newline processing mode, leading to sudden changes when modifying the input.
This alleged "hack" of a reparse isn't that bad IMO, not really an overhead or anything considering a reparse is done anyway for every single input change
=> fix: re-parse when switching modes

src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/editor/EditorRoute.kt
Fixes #87
Ugly code but this at least preserves all other placeholders while filtering out the invalid ones
Also replaces kotlin deprecated `minutes(Int): Duration` with `Int.minutes extension property from Duration.Companion`
=> fix: Try-catch around constructing placeholders

src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Fixes inputs such as https://webui.adventure.kyori.net/?mode=chat_open&input=%3Cclick%3Arun_command%3A"%3Cred%3Etest"%3EClick%20here%21
=> fix: Use HTML builder for click event toast so HTML inside is escaped

src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
This reduces extreme nesting and better matches the style with which promises are used in within javascript, and we're technically using javascript API here.
Note that this *technically* relies on a workaround to a bug, see <https://youtrack.jetbrains.com/issue/KT-19672>
=> style: Prefer chaining Promise.then rather than nesting them

build.gradle.kts, gradle/libs.versions.toml, src/commonMain/kotlin/net/kyori/adventure/webui/Constants.kt, src/commonMain/kotlin/net/kyori/adventure/webui/websocket/Packet.kt, src/commonMain/resources/web/css/style.css, src/commonMain/resources/web/index.html, src/jsMain/kotlin/net/kyori/adventure/webui/js/BytebinStorage.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/CopyModal.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/ExternalFunctions.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/Mode.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/PersistentStorage.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/StyleButtons.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/storage/BytebinStorage.kt
WIP! has lots of TODOs
Partially implements #51
Allow for sharing short links for saved input, using [bytebin](https://github.com/lucko/bytebin) as longer term storage.  
Due to indecisiveness, I've implemented the bytebin-related logic on both client- and server-side, ~~with just a const bool to choose. In server-side mode, the server essentially acts as a direct proxy to bytebin as it does almost no additional logic on its end, so the web requests make sense to put on the client instead. Additionally, I needed to add an http client as a dependency on the jvm side for this one single purpose.
However, there might be some merit to the more "abstract" implementation of it being on the server, perhaps making it easier to swap it out or something, with better access control etc.~~
Since …
=> feat: Short links!

src/jsMain/kotlin/net/kyori/adventure/webui/js/Background.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Consider the following link: <https://webui.adventure.kyori.net/?x=JDPtIK5fM4>
It is in server list mode but doesn't set the proper background for it, this PR fixes that
=> fix: Properly reload background when loading link with server list mode

src/jsMain/kotlin/net/kyori/adventure/webui/js/HoverManager.kt
Fixes #113 
just a typo using the wrong variable, makes no sense to subtract the *width* when modifying the height.
Also moves comments around because their indentation made them appear to apply to the wrong section
=> fix: use correct variable to disallow tooltip to go off bottom of screen

src/commonMain/resources/web/css/style.css, src/commonMain/resources/web/index.html, src/jsMain/kotlin/net/kyori/adventure/webui/js/StyleButtons.kt
Closes #118. Was originally planned as part of #56 but didn't make it.
Note that this whole addition is disabled on mobile because of width concerns.
https://user-images.githubusercontent.com/53803019/173894990-85113e4a-9a04-4aa5-a4bf-2c9c81663121.mp4
=> Add clickable swatches for each of the 16 "named" colors

src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
Closes #119. This allows it to properly handle and modify text nodes without affecting children
=> fix: operate on Node instead of Element when obfuscating

build.gradle.kts, src/commonMain/kotlin/net/kyori/adventure/webui/BuildInfo.kt, src/commonMain/kotlin/net/kyori/adventure/webui/Constants.kt, src/jsMain/kotlin/net/kyori/adventure/webui/js/BytebinStorage.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/storage/BytebinStorage.kt, src/jvmMain/resources/application.conf
Closes #16. Closes #109.
Adds the endpoint `/api/build`, which returns
* server start time,
* adventure-text-minimessage version,
* webui commit hash at build time, and
* configured bytebin URL (https://bytebin.lucko.me by default)
These are mostly set through application.conf. The client will check this build endpoint to determine what bytebin instance to use, then cache it for next time
=> Build info endpoint

src/commonMain/resources/web/index.html, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt
This shouldn't normally happen, but if it does, previous the input would simply stop working. With this change, it displays a warning
It could also attempt to reconnect or something, but given that a websocket closure should *only* happen in weird cases, such as losing all internet connection, I have low confidence in a reconnect being successful at all. The user can simply manually do a reconnect by using the refresh button anyway
=> Listen for when the websocket closes and display a warning

.github/workflows/deploy.yml, Dockerfile, build.gradle.kts, docker-compose.yml, gradle/libs.versions.toml, readme.md
This replaces the old manual Dockerfile, which had implicit dependencies on certain gradle tasks being run already and resulted in another spot to configure options.
[Jib](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin) unifies build and runtime configuration within one file, and is intended to build more disk-efficient docker images as well.
=> feat: Deploy docker images using Jib

src/jsMain/kotlin/net/kyori/adventure/webui/js/PersistentStorage.kt
Apparently URLSearchParams.get does all the encoding for you. Doing it again will break things.
=> fix: Don't url-decode something already url-decoded

readme.md
I've made a minor adjustment to correct the domain for the GitHub Container Registry. The correct domain is `ghcr.io` instead of `ghrc.io`. Additionally, I've ensured that Docker image names comply with Docker conventions by converting them to all lowercase.
=> Fix: Docker image name

src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/hook/StandardRenderHooks.kt
The colour selected for text shadows doesn't currently match the game, and is often way too bright. For example, `<#ffff00>example`, in-game and in the viewer:
This PR uses the same logic as the game (see `net.minecraft.client.gui.Font.StringRenderOutput#dimFactor`).
=> fix: Correct text shadow colour

src/commonMain/kotlin/net/kyori/adventure/webui/Constants.kt, src/commonMain/kotlin/net/kyori/adventure/webui/websocket/Packet.kt, src/commonMain/resources/web/index.html, src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/preview/ServerStatusPreviewManager.kt
settled for a simple button unless somebody has a better idea
the button has to be pressed again to update the preview
=> feat: add simple frontend for in-game preview, closes #178

gradle/libs.versions.toml, src/commonMain/resources/web/css/style.css, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/MiniMessage.kt, src/jvmMain/kotlin/net/kyori/adventure/webui/jvm/minimessage/hook/StandardRenderHooks.kt
today in "abby attempts to do web," text shadows
=> feat: text shadow support and adveture 4.18.0 bump
